// js/bacterias.js
/*
 * Micro Lab Assist
 * Sistema Especialista para Identificação Microbiológica
 *
 * Copyright (C) 2026 Júlio César Martins
 *
 * Licensed under the GNU Affero General Public License v3.0
 *
 * Repositório:
 * https://github.com/Corvo-UFMG/MicroLab-Assist
 */
const bacterias = [
  {
    "nome": "Eikenella corrodens",
    "grupo": "Bacilo Gram-negativo fastidioso",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreção de mordedura humana, abscessos cervicais, infecções por mordedura, endocardite",
    "habitat": "Microbiota normal da cavidade oral e trato respiratório superior humano",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Coccobacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo", // Apresenta "twitching motility" (mecanismo de estiramento), mas no teste clássico de motilidade em tubo é considerado negativo
      "Respiracao": "Facultativo",
      "Atmosfera": "Capnofílica", // Cresce muito melhor na presença de CO2 (capnofílica) ou em anaerobiose
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena", // Colônias pequenas que frequentemente "escavam" ou corroem o ágar (daí o nome corrodens)
      "Hemolise": "Gama", // Pode apresentar uma leve coloração esverdeada (alfa-hemólise) ao redor da colônia após 48h, mas classicamente é gama
      "Tipo de colonia em MacConkey": "Não cresce", // Sendo um fastidioso (HACEK), ela geralmente não cresce em meio seletivo como MacConkey
      "Fermentacao lactose": "Não se aplica", // Como não cresce no MacConkey, não se avalia a fermentação clássica de lactose por essa via
      "EMB": "Não cresce",
      "Pigmento": "Ausente", // Pode amarelecer levemente com o tempo, mas classicamente sem pigmento forte
      "Aspecto colonia": "Corrosivo", // Característica marcante de "entrar" para dentro do ágar e exalar odor de água sanitária (cloro)
      "Catalase": "Negativo",
      "Oxidase": "Positivo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "Inerte", // Não fermenta carboidratos no TSI (não altera o tubo ou permanece K/K)
      "SIM": "Negativo/Negativo/Negativo", // (Indol, Sulfeto, Motilidade todos negativos)
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Positivo", // Uma das reações bioquímicas positivas importantes para ela
      "Ornitina": "Positivo", // Também positiva, ajuda a fechar o diagnóstico diferencial
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica", // Mecanismos de resistência típicos de enterobactérias não se aplicam diretamente aqui
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Escherichia coli",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, fezes, sangue, secreções cirúrgicas",
    "habitat": "Microbiota normal do trato gastrointestinal humano e de animais",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Variável",
      "Esporos": "Ausente",
      "Motilidade": "Positivo", // A grande maioria das cepas é móvel
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média", // Geralmente colônias cinzentas e úmidas
      "Hemolise": "Variável", // Pode ser gama ou beta-hemolítica (frequente em isolados urinários)
      "Tipo de colonia em MacConkey": "Rosa/Vermelha", // Cresce muito bem e é fermentadora de lactose
      "Fermentacao lactose": "Positivo",
      "EMB": "Verde metálico", // Característica clássica de reflexo esverdeado no meio EMB
      "Pigmento": "Ausente",
      "Aspecto colonia": "Úmido",
      "Catalase": "Positivo",
      "Oxidase": "Negativo", // Padrão ouro para diferenciar enterobactérias de não-fermentadores
      "Coagulase": "Não se aplica",
      "Indol": "Positivo", // Teste chave para identificação rápida de E. coli
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "A/A", // Fermenta glicose e lactose com produção de ácido (tudo amarelo) e gás
      "SIM": "Positivo/Positivo/Positivo", // Geralmente Móvel (+), Indol (+) e H2S (-)
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Positivo",
      "Ornitina": "Variável",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Variável", // Pode apresentar o mecanismo dependendo do perfil de resistência
      "AmpC": "Variável",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  { 
    "nome": "Staphylococcus aureus",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreções purulentas, abscessos, sangue, ponta de cateter",
    "habitat": "Microbiota normal da pele e fossas nasais",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Agrupados (Cachos)",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média", // Colônias lisas, frequentemente douradas ou brancas
      "Hemolise": "Beta", // Classicamente apresenta uma zona nítida de beta-hemólise
      "Tipo de colonia em MacConkey": "Não cresce", // Meio inibe o crescimento de Gram-positivos
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Dourado", // Pode ser amarelo/dourado (daí o nome aureus)
      "Aspecto colonia": "Cremoso",
      "Catalase": "Positivo", // Diferencia Staphylococcus (+) de Streptococcus (-)
      "Oxidase": "Negativo",
      "Coagulase": "Positivo", // Teste definitivo para S. aureus
      "Indol": "Negativo",
      "Urease": "Positivo",
      "Citrato": "Variável",
      "TSI": "A/A", // Fermenta carboidratos acidificando o meio, sem H2S
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Variável",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Positivo",
      "DNase": "Positivo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Variável", // Pode ser uma cepa MRSA (Resistente à Oxacilina/Cefoxitina) ou MSSA (Sensível)
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Pseudomonas aeruginosa",
    "grupo": "Bacilo Gram-negativo Não Fermentador",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreção traqueal, urina, ponta de cateter, feridas de queimadura",
    "habitat": "Ambiente úmido, solo, água, ambiente hospitalar",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Variável",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Aeróbia",
      "Temperatura de Crescimento": "35-42°C", // Cresce bem até a 42°C (teste diferencial)
      "Tipo de colonia em Agar sangue": "Grande", // Colônias espalhadas, aspecto metálico/iridescente
      "Hemolise": "Beta", // Geralmente fortemente beta-hemolítica
      "Tipo de colonia em MacConkey": "Incolor", // Cresce bem, mas não fermenta lactose (lactose negativa)
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Verde/Azulado", // Produz piocianina e pioverdina (colônia e meio ficam verdes)
      "Aspecto colonia": "Metálico", // Odor característico de uva ou adocicado
      "Catalase": "Positivo",
      "Oxidase": "Positivo", // Diferencial crítico: separa Pseudomonas de enterobactérias
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Variável",
      "Citrato": "Positivo",
      "TSI": "K/K", // Não fermenta açúcar nenhum (Alcalino/Alcalino ou Inerte)
      "SIM": "Negativo/Negativo/Positivo", // Indol (-), H2S (-), Motilidade (+)
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Positivo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica",
      "AmpC": "Variável",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Klebsiella pneumoniae",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Escarro, urina, sangue, secreção traqueal",
    "habitat": "Trato gastrointestinal e respiratório de humanos e ambiente",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Presente", // Cápsula muito espessa, marca registrada da espécie
      "Esporos": "Ausente",
      "Motilidade": "Negativo", // Característica importante: enterobactéria imóvel
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Grande",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Rosa/Mucoide", // Fortemente fermentadora de lactose e muito viscosa
      "Fermentacao lactose": "Positivo",
      "EMB": "Rosa/Roxo escuro", // Sem brilho metálico
      "Pigmento": "Ausente",
      "Aspecto colonia": "Mucoide", // Colônias brilhantes e "gumentas" devido à cápsula
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo", // Klebsiella pneumoniae típica é indol negativa (diferente da K. oxytoca)
      "Urease": "Positivo", // Geralmente urease positiva lenta/fraca
      "Citrato": "Positivo",
      "TSI": "A/A", // Fermenta glicose e lactose com muito gás
      "SIM": "Negativo/Negativo/Negativo", // Totalmente imóvel e sem indol/H2S
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Positivo",
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo",
      "PYR": "Negativo",
      "ESBL": "Variável",
      "AmpC": "Variável",
      "KPC": "Variável", // Famosa pelas cepas produtoras de carbapenemase
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Streptococcus agalactiae (Grupo B)",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreção vaginal/retal de gestantes, sangue neonatal, líquor",
    "habitat": "Trato gastrointestinal inferior e trato geniturinário feminino",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Cadeias", // Cadeias curtas ou médias
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena",
      "Hemolise": "Beta", // Apresenta uma zona estreita e discreta de beta-hemólise (às vezes quase imperceptível)
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Cremoso",
      "Catalase": "Negativo", // Diferencial crucial de Staphylococcus
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "A/A", // Fermenta açúcares sem gás no fundo do tubo se for forçado a crescer lá
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo", // Diferencia do Streptococcus pyogenes (que é PYR positivo)
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Salmonella enterica",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Fezes (coprocultura), sangue (hemocultura), urina",
    "habitat": "Trato gastrointestinal de animais e humanos, água e alimentos contaminados",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Positivo",
      "TSI": "K/A", // Alcalino/Ácido (Fermenta glicose, mas não lactose)
      "SIM": "Negativo/Positivo/Positivo", // Indol (-), H2S (+), Motilidade (+)
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Positivo",
      "Ornitina": "Positivo",
      "Arginina": "Variável",
      "H2S": "Positivo", // Produção forte de gás sulfídrico (colônia preta no TSI/SS)
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Variável",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Shigella sonnei",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Fezes (coprocultura)",
    "habitat": "Exclusivo do trato gastrointestinal humano (transmissão fecal-oral)",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo", // Importante: enterobactéria imóvel
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo", // Sonnei pode ser fermentadora tardia, mas na leitura padrão é negativa
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "K/A", // Fermenta apenas glicose sem gás
      "SIM": "Negativo/Negativo/Negativo", // Totalmente inerte no SIM
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Positivo", // Diferencial de outras Shigellas que são ornitina negativas
      "Arginina": "Negativo",
      "H2S": "Negativo", // Não produz H2S (diferencia de Salmonella)
      "ONPG": "Positivo", // Positivo tardio
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Variável",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Proteus mirabilis",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, feridas, sangue",
    "habitat": "Trato gastrointestinal humano, solo e água",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Véu de Proteus", // Efeito Swarming (Invasão/ondas na placa)
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Espalhado", // Odor característico de gema de ovo podre/peixe estragado
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo", // P. mirabilis é Indol (-), P. vulgaris é Indol (+)
      "Urease": "Positivo", // Urease fortemente positiva (muda a cor muito rápido)
      "Citrato": "Variável",
      "TSI": "K/A",
      "SIM": "Negativo/Positivo/Positivo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Positivo",
      "Arginina": "Negativo",
      "H2S": "Positivo",
      "ONPG": "Negativo",
      "Gelatinase": "Positivo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Variável",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Enterobacter cloacae",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, sangue, secreção respiratória, feridas",
    "habitat": "Ambiente, fezes humanas e de animais",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Variável",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Rosa", // Fermenta lactose
      "Fermentacao lactose": "Positivo",
      "EMB": "Rosa/Roxo escuro",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Variável",
      "Citrato": "Positivo",
      "TSI": "A/A", // Fermenta glicose e lactose com gás
      "SIM": "Negativo/Negativo/Positivo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Negativo", // Diferencia de Klebsiella pneumoniae (que é Lisina +)
      "Ornitina": "Positivo", // Diferencia de Klebsiella pneumoniae (que é Ornitina -)
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Variável",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo", // Resistência cromossômica clássica (grupo SPACE)
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Acinetobacter baumannii",
    "grupo": "Bacilo Gram-negativo Não Fermentador",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreção traqueal, ponta de cateter, urina, sangue",
    "habitat": "Ambiente hospitalar, superfícies secas, pele de pacientes",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo", // Muitas vezes assume forma de Coccobacilo (parece coco ao microscópio)
      "Arranjo": "Apares/Isolados",
      "Capsula": "Presente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo", // Imóvel (mas exibe motilidade por "twitched" em superfícies)
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Aeróbia",
      "Temperatura de Crescimento": "35-44°C", // Cresce muito bem a 44°C
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama", // Algumas cepas podem dar uma leve alfa ou beta discreta
      "Tipo de colonia em MacConkey": "Incolor", // Cresce bem, mas às vezes ganha tom levemente esbranquiçado/azulado
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo", // Crítico: Diferencia de Pseudomonas aeruginosa (Oxidase +)
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Variável",
      "Citrato": "Positivo",
      "TSI": "K/K", // Inerte (Não fermenta nenhum carboidrato)
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Positivo",
      "KPC": "Variável", // Alta taxa de multirresistência a carbapenêmicos
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Staphylococcus epidermidis",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Média",
    "materiaisAssociados": "Hemocultura (contaminação ou cateter), ponta de cateter, próteses",
    "habitat": "Microbiota normal da pele humana (principal componente)",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Agrupados", // Cachos de uva
      "Capsula": "Ausente", // Produtor de Biofilme (Slime)
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama", // Geralmente não hemolítico
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Branco", // Colônias brancas como giz (diferente do dourado do S. aureus)
      "Aspecto colonia": "Cremoso",
      "Catalase": "Positivo", // Catalase positivo (Staphylococcus)
      "Oxidase": "Negativo",
      "Coagulase": "Negativo", // Diferencial de ouro: Staphylococcus Coagulase Negativo (SCN)
      "Indol": "Negativo",
      "Urease": "Positivo",
      "Citrato": "Variável",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Variável",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica", // Pode ser resistente à oxacilina (Mora no perfil de SCN)
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Sensível",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Staphylococcus saprophyticus",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina (comum em mulheres jovens do sexo feminino)",
    "habitat": "Trato gastrointestinal e reto, pele periuretral",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Agrupados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Branco/Amarelado",
      "Aspecto colonia": "Cremoso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Negativo", // Outro Coagulase Negativo
      "Indol": "Negativo",
      "Urease": "Positivo",
      "Citrato": "Negativo",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Novobiocina": "Resistente",// Nota de bancada: Resistente à Novobiocina (teste definitivo para diferenciar de S. epidermidis)
      "Optoquina": "Não se aplica",
      "Maltose": "Não se aplica"
     }
   },
   {
    "nome": "Streptococcus pneumoniae",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Escarro, líquor, sangue, secreção de ouvido médio",
    "habitat": "Trato respiratório superior (nasofaringe) de humanos",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco", // Diplococos lançolados (formato de chama de vela)
      "Arranjo": "Apares",
      "Capsula": "Presente", // Cápsula polissacarídica muito proeminente
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Microaerófila (Requer 5-10% CO2)",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena", // Colônias com depressão central (aspecto de moeda/tabuleiro de xadrez)
      "Hemolise": "Alfa", // Hemólise verde/parcial (em aerobiose)
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Mucoide", // Autólise após 24-48h gera o centro afundado
      "Catalase": "Negativo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Sensível", // Nota de bancada: Sensível à Optoquina e Solúvel em Bile
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
   },
   {
    "nome": "Enterococcus faecalis",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, sangue, feridas cirúrgicas abdominal, endocardite",
    "habitat": "Trato gastrointestinal humano e de animais",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Apares/Cadeias", // Cadeias curtas ou pares
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "10-45°C", // Tolerância térmica extrema (cresce a 45°C)
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama", // Maioria das vezes não hemolítico (pode dar alfa fraca)
      "Tipo de colonia em MacConkey": "Pequena/Rosa", // Curiosidade: consegue crescer em MacConkey dando microcolônias vermelhas
      "Fermentacao lactose": "Positivo",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Cremoso",
      "Catalase": "Negativo", // Falso negativo (pode dar pseudocatalase muito fraca se crescer em sangue)
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Positivo",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Variável",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo", // Teste chave para o grupo D
      "PYR": "Positivo", // Teste definitivo (Bile Esculina + e PYR + = Enterococcus)
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Variável", // Cepas resistentes à vancomicina são críticas no hospital
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
{
    "nome": "Streptococcus pyogenes (Grupo A)",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Swab de orofaringe, secreção de feridas, sangue",
    "habitat": "Trato respiratório superior e pele de humanos",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Cadeias", // Cadeias longas
      "Capsula": "Presente", //em algumas cepas mucoides
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia (Melhora com CO2)",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena", // Colônias pontiformes (tipo gota de orvalho)
      "Hemolise": "Beta", // Zona de beta-hemólise muito larga, nítida e transparente
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Negativo", // Streptococcus
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Positivo",
      "Bile Esculina": "Negativo",
      "PYR": "Positivo", // Diferencial absoluto de S. agalactiae (PYR +)
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica", // Nota de bancada: Sensível à Bacitracina
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
{
    "nome": "Serratia marcescens",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, secreção respiratória, sangue, infecção de ferida cirúrgica",
    "habitat": "Ambiente, água, solo e superfícies hospitalares",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor", // Fermentador lento/tardio de lactose (pode parecer incolor em 24h)
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Vermelho/Rosa", // Algumas cepas produzem o pigmento prodigiosina (temp. ambiente)
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Positivo",
      "TSI": "A/A", // Fermenta sacarose/glicose dando tom ácido no bisel
      "SIM": "Negativo/Negativo/Positivo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Positivo",
      "Ornitina": "Positivo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Positivo", // Triade enzimática clássica: Gelatinase (+), DNase (+), Lipase (+)
      "DNase": "Positivo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo", // Resistência induzível (grupo SPACE)
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Stenotrophomonas maltophilia",
    "grupo": "Bacilo Gram-negativo Não Fermentador",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreção traqueal, sangue, urina, ponta de cateter",
    "habitat": "Ambiente úmido, água, soluções hospitalares",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Aeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média", // Pigmento amarelo-esverdeado ou lavanda no ágar
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Amarelo/Esverdeado",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo", // Chave: Diferencia da Pseudomonas aeruginosa (Oxidase +)
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Positivo",
      "TSI": "K/K",
      "SIM": "Negativo/Negativo/Positivo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Positivo", // Característica forte (Lisina Decarboxilase +)
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Positivo",
      "DNase": "Positivo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Burkholderia cepacia",
    "grupo": "Bacilo Gram-negativo Não Fermentador",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Escarro/secreção traqueal (fibrose cística), sangue",
    "habitat": "Ambiente úmido, solo, água, desinfetantes contaminados",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Aeróbia",
      "Temperatura de Crescimento": "30-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Amarelo/Castanho",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Positivo", // Fracamente positiva/variável na prática
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Variável",
      "Citrato": "Positivo",
      "TSI": "K/K",
      "SIM": "Negativo/Negativo/Positivo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Positivo",
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Variável",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Morganella morganii",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, infecção de ferida, sangue",
    "habitat": "Trato gastrointestinal de humanos e animais",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso", // Não faz swarming/véu no ágar (diferente do Proteus)
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Positivo", // Chave: Indol (+)
      "Urease": "Positivo", // Urease fortemente positiva
      "Citrato": "Negativo",
      "TSI": "K/A",
      "SIM": "Positivo/Negativo/Positivo", // Indol (+), H2S (-), Motilidade (+)
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Positivo",
      "Arginina": "Negativo",
      "H2S": "Negativo", // Não produz H2S (diferencia do Proteus mirabilis)
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Citrobacter freundii",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, vesícula biliar, sangue, feridas",
    "habitat": "Trato intestinal, solo, água e alimentos",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Rosa/Incolor", // Variável (lactose tardia ou positiva)
      "Fermentacao lactose": "Variável",
      "EMB": "Rosa/Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Variável",
      "Urease": "Variável",
      "Citrato": "Positivo", // Citrato (+)
      "TSI": "A/A",
      "SIM": "Variável/Positivo/Positivo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Variável",
      "H2S": "Positivo", // Produção de H2S (confunde com Salmonella no TSI)
      "ONPG": "Positivo", // Chave: ONPG (+) diferencia da Salmonella (que é ONPG -)
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Variável",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Enterococcus faecium",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Sangue, urina, infecção intra-abdominal, cateter",
    "habitat": "Trato gastrointestinal humano e de animais",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Apares/Cadeias",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "10-45°C",
      "Tipo de colonia em Agar sangue": "Pequena/Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Variável",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Cremoso",
      "Catalase": "Negativo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Positivo",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo",
      "PYR": "Positivo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Variável", // Altíssima taxa de resistência à Vancomicina comparado ao faecalis
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Listeria monocytogenes",
    "grupo": "Bacilo Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Líquor (meningite), sangue, placenta/material fetal",
    "habitat": "Alimentos contaminados (queijos, embutidos), solo, animais",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Bacilo", // Bacilos Gram-positivos curtos (parece Coccobacilo)
      "Arranjo": "Isolados/Apares",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo", // Motilidade característica em "cambalhota" a 25°C (imóvel a 37°C)
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "4-45°C", // Cresce sob refrigeração (geladeira)
      "Tipo de colonia em Agar sangue": "Pequena",
      "Hemolise": "Beta", // Beta-hemólise muito estreita e discreta sob a colônia
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo", // Chave: Diferencia do Streptococcus agalactiae (Catalase -)
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "A/A",
      "SIM": "Negativo/Negativo/Positivo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo", // Positiva (confunde com Enterococcus no Gram se não olhar a forma)
      "PYR": "Variável",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Corynebacterium diphtheriae",
    "grupo": "Bacilo Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Swab de nasofaringe/orofaringe (pseudomembrana)",
    "habitat": "Trato respiratório e pele humana",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Bacilo", // Bacilos pleomórficos em forma de clava (letras chinesas)
      "Arranjo": "Palisada",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama", // Pode apresentar discreta beta
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Cinza/Preto", // Em meios seletivos com Telurito de Potássio (Tinsdale)
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo", // Diferencial de Corynebacterium pseudodiphtheriticum (Urease +)
      "Citrato": "Negativo",
      "TSI": "Não se aplica",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Yersinia enterocolitica",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Fezes (coprocultura), sangue, apêndice",
    "habitat": "Trato intestinal de suínos, animais e água contaminada",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo", // Coccobacilo pequeno
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo", // Móvel a 22-25°C, mas IMÓVEL a 37°C (Caractere psicrófilo)
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "22-37°C",
      "Tipo de colonia em Agar sangue": "Pequena",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso", // "Olho de boi" no ágar CIN
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Variável",
      "Urease": "Positivo", // Urease Positiva
      "Citrato": "Negativo",
      "TSI": "A/A", // Fermenta Sacarose
      "SIM": "Variável/Negativo/Positivo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Variável",
      "Lisina": "Negativo",
      "Ornitina": "Positivo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Campylobacter jejuni",
    "grupo": "Bacilo Gram-negativo Curvo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Fezes (coprocultura)",
    "habitat": "Trato gastrointestinal de aves de capoeira e animais",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo", // Forma de gaivota/S ou espiral
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo", // Motilidade em "saca-rolhas"
      "Respiracao": "Microaerófilo", // Requer 5% O2, 10% CO2
      "Atmosfera": "Microaerófila",
      "Temperatura de Crescimento": "42°C", // Termofílico (cresce a 42°C)
      "Tipo de colonia em Agar sangue": "Pequena/Espalhada",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce", // Não cresce na maioria dos MacConkeys padrão
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Gota de água",
      "Catalase": "Positivo",
      "Oxidase": "Positivo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "K/K", // Não fermenta carboidratos via via clássica
      "SIM": "Negativo/Negativo/Positivo",
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
{
    "nome": "Haemophilus influenzae",
    "grupo": "Bacilo Gram-negativo Fastidioso",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "LCR, sangue, escarro, secreção de ouvido, aspirado nasofaríngeo",
    "habitat": "Trato respiratório superior humano",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Coccobacilo",
      "Arranjo": "Isolados",
      "Capsula": "Presente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Capnofílica", // Requer 5-10% CO2
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Não cresce", // Requer Fator X e V (cresce em Ágar Chocolate ou via Satelitismo)
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Positivo",
      "Coagulase": "Não se aplica",
      "Indol": "Variável",
      "Urease": "Positivo",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Variável",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Neisseria meningitidis",
    "grupo": "Diplococo Gram-negativo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "LCR, sangue (meningococcemia), nasofaringe, raspado de lesão de pele",
    "habitat": "Nasofaringe humana",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Coco", // Diplococo em grão de café
      "Arranjo": "Apares",
      "Capsula": "Presente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Capnofílica",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena", // Cresce em Ágar Sangue e Ágar Chocolate
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Positivo", // Chave de Neisseria: Oxidase (+), Catalase (+)
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Positivo"
    }
  },
  {
    "nome": "Neisseria gonorrhoeae",
    "grupo": "Diplococo Gram-negativo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Secreção uretral, swab endocervical, secreção ocular, secreção faríngea",
    "habitat": "Trato urogenital humano",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Coco", // Diplococo intramacrofágico clássico
      "Arranjo": "Apares",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Capnofílica",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Não cresce", // Exigente: Requer Ágar Chocolate ou Thayer-Martin
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Positivo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Negativo"
    }
  },
  {
    "nome": "Moraxella catarrhalis",
    "grupo": "Diplococo Gram-negativo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Escarro, secreção traqueal, secreção de ouvido, nasofaringe",
    "habitat": "Trato respiratório humano",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Coco", // Diplococo Gram-negativo
      "Arranjo": "Apares",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Aeróbio obrigatório",
      "Atmosfera": "Aeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena", // Colônia estilo "disco de hóquei" (desliza no ágar intacta)
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Positivo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "Inerte",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Positivo", // Chave diferencial em relação às Neisserias (Moraxella é DNase +)
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Proteus vulgaris",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, infecção de ferida, sangue",
    "habitat": "Trato intestinal, solo, água",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Onda (Swarming)", // Fenômeno do véu/swarming no ágar
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Positivo", // Chave diferencial do P. mirabilis (vulgaris é Indol POSITIVO)
      "Urease": "Positivo", // Urease hiperativa
      "Citrato": "Variável",
      "TSI": "A/A", // Fermenta sacarose (diferente do mirabilis K/A)
      "SIM": "Positivo/Positivo/Positivo", // Indol (+), H2S (+), Motilidade (+)
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo", // P. mirabilis é Ornitina (+), P. vulgaris é (-)
      "Arginina": "Negativo",
      "H2S": "Positivo",
      "ONPG": "Negativo",
      "Gelatinase": "Positivo",
      "DNase": "Negativo",
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Klebsiella oxytoca",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina, sangue, secreção respiratória, secreção abdominal",
    "habitat": "Trato gastrointestinal humano, ambiente hospitalar",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Presente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo", // Imóvel clássica (assim como a K. pneumoniae)
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Grande/Mucóide",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Rosa",
      "Fermentacao lactose": "Positivo",
      "EMB": "Rosa/Escuro",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Mucóide",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Positivo", // Chave diferencial absoluta: K. oxytoca é Indol (+), K. pneumoniae é Indol (-)
      "Urease": "Positivo",
      "Citrato": "Positivo",
      "TSI": "A/A",
      "SIM": "Negativo/Positivo/Negativo", // H2S (-), Indol (+), Motilidade (-)
      "Vermelho de Metila": "Variável",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Positivo",
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Variável",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Providencia stuartii",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Urina (pacientes idosos/cateterizados), feridas de queimadura, sangue",
    "habitat": "Ambiente hospitalar, trato intestinal",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor",
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Positivo",
      "Urease": "Variável", // Frequentemente fraco ou tardio
      "Citrato": "Positivo",
      "TSI": "K/A",
      "SIM": "Negativo/Positivo/Positivo", // H2S (-), Indol (+), Motilidade (+)
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Variável",
      "AmpC": "Positivo",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Streptococcus viridans",
    "grupo": "Coco Gram-positivo",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Sangue (endocardite bacteriana), biópsia de valva cardíaca, abscesso dental",
    "habitat": "Cavidade oral, trato respiratório e gastrointestinal humano",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Cadeias",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Capnofílica",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena",
      "Hemolise": "Alfa", // Alfa-hemolítico clássico (verde no ágar)
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Negativo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Não se aplica",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo", // Chave: Negativo para Bile Esculina (diferencia de Enterococcus)
      "PYR": "Negativo", // PYR negativo (diferencia de S. pyogenes e Enterococcus)
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Resistente",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Clostridium perfringens",
    "grupo": "Bacilo Gram-positivo Anaeróbio",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Biópsia de tecido necrosado (gangrena gasosa), sangue, aspirado de abscesso",
    "habitat": "Solo, trato intestinal de humanos e animais",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Bacilo", // Bacilos Gram-positivos retangulares grandes ("em bloco")
      "Arranjo": "Isolados/Apares",
      "Capsula": "Presente",
      "Esporos": "Presente", // Esporos raramente vistos no material clínico direto
      "Motilidade": "Negativo", // Imóvel (exceção entre os Clostridium)
      "Respiracao": "Anaeróbio obrigatório",
      "Atmosfera": "Anaeróbia",
      "Temperatura de Crescimento": "35-45°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Beta", // Dupla zona de hemólise característica no ágar sangue anaeróbio
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Negativo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "A/A", // Produção volumosa de gás
      "SIM": "Negativo/Negativo/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Positivo",
      "ONPG": "Não se aplica",
      "Gelatinase": "Positivo",
      "DNase": "Negativo",
      "Bile Esculina": "Não se aplica",
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Bacteroides fragilis",
    "grupo": "Bacilo Gram-negativo Anaeróbio",
    "importanciaClinica": "Alta",
    "materiaisAssociados": "Aspirado de abscesso intra-abdominal, sangue, secreção de ferida pélvica/peritoneal",
    "habitat": "Trato gastrointestinal humano (microbiota anaeróbia dominante)",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo", // Bacilos pleomórficos
      "Arranjo": "Isolados",
      "Capsula": "Presente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Anaeróbio obrigatório",
      "Atmosfera": "Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Não cresce",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Não cresce",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso",
      "Catalase": "Positivo", // Catalase positiva (resistente à bile no BBE)
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Variável",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Negativo/Variável/Negativo",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Negativo",
      "ONPG": "Não se aplica",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo", // Cresce e hidrolisa bile esculina no meio BBE
      "PYR": "Não se aplica",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
{
    "nome": "Klebsiella aerogenes",
    "grupo": "Bacilo Gram-negativo (Enterobactéria)",
    "importanciaClinica": "Alta (Infecções hospitalares, ITU, bacteremia, pneumonia associada à ventilação)",
    "materiaisAssociados": "Urina, secreção traqueal, sangue, feridas cirúrgicas",
    "habitat": "Microbiota intestinal humana e de animais, ambiente hospitalar e solo",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados ou aos pares",
      "Capsula": "Presente", // Menos espessa que a de K. pneumoniae, mas pode dar aspecto mucóide
      "Esporos": "Ausente",
      "Motilidade": "Positivo", // Diferencial chave contra K. pneumoniae e K. oxytoca (que são imóveis)
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média/Grande",
      "Hemolise": "Gama", // Geralmente não hemolítico
      "Tipo de colonia em MacConkey": "Rosa/Vermelha", // Fermenta lactose tardiamente ou rapidamente
      "Fermentacao lactose": "Positivo",
      "EMB": "Púrpura/Rosa sem brilho metálico",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Úmido/Mucóide",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Negativo", // Importante diferencial
      "Urease": "Variável", // Frequentemente fraca ou negativa
      "Citrato": "Positivo",
      "TSI": "A/A", // Fermenta glicose e lactose com gás
      "SIM": "Positivo/Negativo/Negativo", // Móvel (+), Indol (-) e H2S (-)
      "Vermelho de Metila": "Negativo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Positivo",
      "Ornitina": "Positivo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo",
      "PYR": "Negativo",
      "ESBL": "Variável",
      "AmpC": "Positivo", // Cromossômica induzível (Risco de resistência a cefalosporinas de 3ª geração)
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Providencia rettgeri",
    "grupo": "Bacilo Gram-negativo (Enterobactéria - Tribu Proteeae)",
    "importanciaClinica": "Média/Alta (Infecções urinárias de repetição, cateteres, surtos hospitalares)",
    "materiaisAssociados": "Urina, feridas, sangue",
    "habitat": "Ambientes aquáticos, solo e microbiota do trato gastrointestinal",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Gama",
      "Tipo de colonia em MacConkey": "Incolor", // Não fermenta lactose
      "Fermentacao lactose": "Negativo",
      "EMB": "Incolor/Amarelado",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso/Úmido",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Positivo",
      "Urease": "Positivo", // Urease fortemente positiva (característica da tribo Proteeae)
      "Citrato": "Positivo",
      "TSI": "K/A", // Fermenta apenas glicose, com produção de gás variável
      "SIM": "Positivo/Positivo/Negativo", // Móvel (+), Indol (+) e H2S (-)
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Negativo",
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Negativo",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Variável",
      "PYR": "Positivo",
      "ESBL": "Variável",
      "AmpC": "Positivo",
      "KPC": "Variável",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Aeromonas hydrophila",
    "grupo": "Bacilo Gram-negativo Não-Enterobactéria (Aeromonadaceae)",
    "importanciaClinica": "Média/Alta (Gastroenterite, infecções de feridas pós-trauma aquático, sepse)",
    "materiaisAssociados": "Fezes, secreções de feridas, sangue, aspirados de tecidos molhados",
    "habitat": "Água doce, esgoto, alimentos e ambiente aquático",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Bacilo",
      "Arranjo": "Isolados ou pares",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Positivo", // Flagelo polar
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "28-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Beta", // Forte zona de beta-hemólise em Ágar Sangue
      "Tipo de colonia em MacConkey": "Incolor ou Rosa claro", // Pode/não fermentar lactose
      "Fermentacao lactose": "Variável",
      "EMB": "Incolor",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso, opaco, redondo",
      "Catalase": "Positivo",
      "Oxidase": "Positivo", // Teste de Ouro para diferenciar de Enterobactérias
      "Coagulase": "Não se aplica",
      "Indol": "Positivo",
      "Urease": "Negativo",
      "Citrato": "Positivo",
      "TSI": "K/A ou A/A",
      "SIM": "Positivo/Positivo/Negativo",
      "Vermelho de Metila": "Positivo",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Positivo",
      "Ornitina": "Negativo",
      "Arginina": "Positivo",
      "H2S": "Negativo",
      "ONPG": "Positivo",
      "Gelatinase": "Positivo", // Hidrolisa gelatina
      "DNase": "Positivo", // Diferencial importante
      "Bile Esculina": "Positivo",
      "PYR": "Variável",
      "ESBL": "Não se aplica",
      "AmpC": "Positivo", // Apresenta carbapenemase/cefalosporinase induzível inerente (CphA)
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Pasteurella multocida",
    "grupo": "Coccobacilo Gram-negativo (Fastidioso)",
    "importanciaClinica": "Alta (Infecções graves de feridas por mordeira/arranhão de cães e gatos)",
    "materiaisAssociados": "Aspirado de feridas, secreções de abscesso, sangue, escarro",
    "habitat": "Microbiota oral e respiratória normal de mamíferos (gatos, cães)",
    "caracteristicas": {
      "Gram": "Negativo",
      "Forma": "Coccobacilo", // Pequenos bacilos com coloração bipolar comum
      "Arranjo": "Isolados ou aos pares",
      "Capsula": "Presente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Microaerófila",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena a Média",
      "Hemolise": "Gama", // Não faz hemólise (odor característico de mofo/musty)
      "Tipo de colonia em MacConkey": "Sem crescimento", // NÃO cresce no Ágar MacConkey
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Sem crescimento",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Liso, acinzentado, pode ser mucóide",
      "Catalase": "Positivo",
      "Oxidase": "Positivo", // Chave na identificação de Pasteurella
      "Coagulase": "Não se aplica",
      "Indol": "Positivo", // Teste chave de diferenciação rápida
      "Urease": "Negativo",
      "Citrato": "Negativo",
      "TSI": "A/A", // Fermenta glicose e sacarose sem gás significativo
      "SIM": "Negativo/Positivo/Negativo", // Imóvel (-), Indol (+) e H2S (-)
      "Vermelho de Metila": "Variável",
      "Voges-Proskauer": "Negativo",
      "Lisina": "Negativo",
      "Ornitina": "Positivo", // Chave para P. multocida
      "Arginina": "Negativo",
      "H2S": "Negativo",
      "ONPG": "Variável",
      "Gelatinase": "Negativo",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Negativo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Staphylococcus lugdunensis",
    "grupo": "Coco Gram-positivo (Estafilococo Coagulase-Negativo de alta virulência)",
    "importanciaClinica": "Alta (Endocardite destrutiva grave, infecções de próteses, osteomielite)",
    "materiaisAssociados": "Sangue, biópsias de tecido, secreção purulenta de feridas",
    "habitat": "Pele humana (especialmente região perineal e inguinal)",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Cacho de uva",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Média",
      "Hemolise": "Beta", // Frequente beta-hemólise marcante (diferente de outros ECN)
      "Tipo de colonia em MacConkey": "Sem crescimento",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Sem crescimento",
      "Pigmento": "Creme/Amarelo claro",
      "Aspecto colonia": "Brilhante, bordas bem definidas, odor de alvejante/queijo",
      "Catalase": "Positivo",
      "Oxidase": "Negativo",
      "Coagulase": "Negativo", // Coagulase em tubo é Negativa (pode dar Fator Clumping/Lâmina positivo)
      "Indol": "Não se aplica",
      "Urease": "Variável",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Não se aplica",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Positivo", // Teste diferencial crucial (ODC Positiva diferencia de outros Staphylococcus)
      "Arginina": "Não se aplica",
      "H2S": "Não se aplica",
      "ONPG": "Variável",
      "Gelatinase": "Não se aplica",
      "DNase": "Negativo",
      "Bile Esculina": "Negativo",
      "PYR": "Positivo", // Tipicamente PYR Positivo
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Variável", // Alvo de mecA (pode ser resistente à Oxacilina)
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Streptococcus gallolyticus",
    "grupo": "Coco Gram-positivo (Grupo D / Antigo S. bovis biotipo I)",
    "importanciaClinica": "Alta (Fortemente associado a Endocardite Infecciosa e Câncer Colorretal)",
    "materiaisAssociados": "Sangue (hemoculturas), vegetação valvar",
    "habitat": "Microbiota do trato gastrointestinal humano e de ruminantes",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Coco",
      "Arranjo": "Pares ou cadeias curtas",
      "Capsula": "Ausente",
      "Esporos": "Ausente",
      "Motilidade": "Negativo",
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Microaerófila",
      "Temperatura de Crescimento": "35-37°C",
      "Tipo de colonia em Agar sangue": "Pequena",
      "Hemolise": "Gama", // Principalmente não hemolítico (ou levemente alfa)
      "Tipo de colonia em MacConkey": "Sem crescimento",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Sem crescimento",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Translucido, liso",
      "Catalase": "Negativo",
      "Oxidase": "Negativo",
      "Coagulase": "Não se aplica",
      "Indol": "Não se aplica",
      "Urease": "Negativo",
      "Citrato": "Não se aplica",
      "TSI": "Não se aplica",
      "SIM": "Não se aplica",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Não se aplica",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Não se aplica",
      "ONPG": "Não se aplica",
      "Gelatinase": "Não se aplica",
      "DNase": "Negativo",
      "Bile Esculina": "Positivo", // Característica marcante do Grupo D
      "PYR": "Negativo", // Chave: Diferencia Streptococcus Grupo D de Enterococcus (que é PYR +)
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Resistente",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
  {
    "nome": "Bacillus cereus",
    "grupo": "Bacilo Gram-positivo Esporulado",
    "importanciaClinica": "Alta (Intoxicação alimentar eméticos/diarreicos, infecções oculares graves, bacteremia)",
    "materiaisAssociados": "Fezes, restos alimentares (arroz, massas), aspirados oculares, sangue",
    "habitat": "Amplo no ambiente, solo, poeira e vegetais",
    "caracteristicas": {
      "Gram": "Positivo",
      "Forma": "Bacilo", // Bacilos grandes com extremidades retas
      "Arranjo": "Cadeias curtas ou longas",
      "Capsula": "Variável",
      "Esporos": "Presente", // Esporo central/subterminal que não deforma o esporângio
      "Motilidade": "Positivo", // Diferencial crucial para Bacillus anthracis (que é imóvel)
      "Respiracao": "Facultativo",
      "Atmosfera": "Aeróbia/Anaeróbia",
      "Temperatura de Crescimento": "10-48°C",
      "Tipo de colonia em Agar sangue": "Grande",
      "Hemolise": "Beta", // Forte beta-hemólise (diferencial de B. anthracis)
      "Tipo de colonia em MacConkey": "Sem crescimento",
      "Fermentacao lactose": "Não se aplica",
      "EMB": "Sem crescimento",
      "Pigmento": "Ausente",
      "Aspecto colonia": "Irregular, fosco, rugoso (aspecto de vidro fosco / 'medusa head' discreto)",
      "Catalase": "Positivo",
      "Oxidase": "Variável",
      "Coagulase": "Não se aplica",
      "Indol": "Não se aplica",
      "Urease": "Variável",
      "Citrato": "Positivo",
      "TSI": "Não se aplica",
      "SIM": "Não se aplica",
      "Vermelho de Metila": "Não se aplica",
      "Voges-Proskauer": "Positivo",
      "Lisina": "Não se aplica",
      "Ornitina": "Não se aplica",
      "Arginina": "Não se aplica",
      "H2S": "Não se aplica",
      "ONPG": "Não se aplica",
      "Gelatinase": "Positivo",
      "DNase": "Positivo",
      "Bile Esculina": "Variável",
      "PYR": "Positivo",
      "ESBL": "Não se aplica",
      "AmpC": "Não se aplica",
      "KPC": "Não se aplica",
      "MRSA": "Não se aplica",
      "VRE": "Não se aplica",
      "Optoquina": "Não se aplica",
      "Novobiocina": "Não se aplica",
      "Maltose": "Não se aplica"
    }
  },
{
  "nome": "Treponema pallidum",
  "grupo": "Espiroqueta (Bactéria Gram-negativa não cultivável)",
  "importanciaClinica": "Alta",
  "materiaisAssociados": "Soro, plasma, liquor, raspados de lesões ativas (cancro duro, roséolas)",
  "habitat": "Patógeno humano obrigatório",
  "caracteristicas": {
    "Gram": "Fraco/Invisível", // Não cora bem no Gram tradicional devido à espessura fina
    "Forma": "Espiroqueta",
    "Arranjo": "Isolados",
    "Capsula": "Ausente",
    "Esporos": "Ausente",
    "Motilidade": "Positivo", // Movimento espiral característico por endoflagelos
    "Respiracao": "Microaerófila",
    "Atmosfera": "Não cultivável em rotina",
    "Temperatura de Crescimento": "Não se aplica",
    "Tipo de colonia em Agar sangue": "Não cresce",
    "Hemolise": "Não se aplica",
    "Tipo de colonia em MacConkey": "Não cresce",
    "Fermentacao lactose": "Não se aplica",
    "EMB": "Não cresce",
    "Pigmento": "Ausente",
    "Aspecto colonia": "Não se aplica",
    "Catalase": "Não se aplica",
    "Oxidase": "Não se aplica",
    "Coagulase": "Não se aplica",
    "Indol": "Não se aplica",
    "Urease": "Não se aplica",
    "Citrato": "Não se aplica",
    "TSI": "Não se aplica",
    "SIM": "Não se aplica",
    "Vermelho de Metila": "Não se aplica",
    "Voges-Proskauer": "Não se aplica",
    "Lisina": "Não se aplica",
    "Ornitina": "Não se aplica",
    "Arginina": "Não se aplica",
    "H2S": "Não se aplica",
    "ONPG": "Não se aplica",
    "Gelatinase": "Não se aplica",
    "DNase": "Não se aplica",
    "Bile Esculina": "Não se aplica",
    "PYR": "Não se aplica",
    "ESBL": "Não se aplica",
    "AmpC": "Não se aplica",
    "KPC": "Não se aplica",
    "MRSA": "Não se aplica",
    "VRE": "Não se aplica",
    "Optoquina": "Não se aplica",
    "Novobiocina": "Não se aplica",
    "Maltose": "Não se aplica"
  }
}
]
